# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5cd277f33f52e61631c9277efa0f94301ea2f774cbdefd934a5a5894e10856600ccca6185f759d82a62f57eab630755378fb54b0ddfe29afa013b298f917edd

test:
  secret_key_base: d31fbe22383960939215e5f46d9be976cba43ad5e68556247c6939546f01333e83fc3ce2590115fbcf38c856c9bfb77e0efb4bda89cb415d432c1273d48ea381

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
